name: Build & Test

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: build-${{ hashFiles('**/Versions.kt') }}
      - name: Build with Gradle
        run: ./gradlew build

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: test-${{ hashFiles('**/Versions.kt') }}
      - name: Run Tests
        run: ./gradlew test
      - name: Generate Coverage Reports
        run: ./gradlew jacocoTestReport
      - name: Upload Coverage Reports to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
